use_frameworks!

target 'AsyncDisplayKit-SnapshotTests_Example' do
  pod 'AsyncDisplayKitSnapshotTests', :path => '../'

  target 'AsyncDisplayKit-SnapshotTests_Tests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase'
    pod 'Texture'
  end
end
